/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as migrationSol from "./Migration.sol";
export type { migrationSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { Migrations } from "./Migration.sol/Migrations";
export { Migrations__factory } from "./factories/Migration.sol/Migrations__factory";
